os: linux
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
